# Generated by Django 6.0.3 on 2026-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entity_city_entity_phone2_entity_woreda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phone2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
