# Generated by Django 6.0.3 on 2026-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entity_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='registration_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='woreda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
