# Generated by Django 6.0.3 on 2026-03-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_entity_city_alter_entity_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('agency', 'Agency'), ('tvet', 'TVET'), ('ocss', 'OCSS')], default='agency', max_length=200),
        ),
    ]
