# Generated by Django 6.0.3 on 2026-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entity_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
