# Generated by Django 6.0.3 on 2026-03-27 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entity_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCorrection',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('correction_type', models.CharField(choices=[('name', 'Name'), ('dob', 'Date of Birth'), ('sex', 'Sex')], max_length=20)),
                ('phone', models.CharField(max_length=200)),
                ('labor_id', models.CharField(blank=True, max_length=200)),
                ('old_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CorrectionRequest',
        ),
    ]
