# Generated by Django 6.0.3 on 2026-03-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientcorrection_delete_correctionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcorrection',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
