# Generated by Django 6.0.3 on 2026-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clientcorrection_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='labor_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='tvet_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('agency', 'Agency'), ('tvet', 'TVET'), ('ossc', 'OSSC')], default='agency', max_length=200),
        ),
    ]
