# Generated by Django 6.0.3 on 2026-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_entity_labor_id_entity_phone3_entity_tvet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcorrection',
            name='correction_type',
            field=models.CharField(choices=[('name', 'Name'), ('dob', 'Date of Birth'), ('sex', 'Sex'), ('too_many_attempt', 'Too Many Attempt')], max_length=20),
        ),
    ]
