# Generated by Django 6.0.3 on 2026-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clientcorrection_correction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcorrection',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
